### ISSUE TITLE
Possible issue with iterator

### ISSUE THREAD

**Issue by mpusz** [Tessil/hopscotch-map#23]
Hi,

I have a code similar to that one:
```
tsl::hopscotch_map<std::string, std::vector<int>> map;
auto it = map.find("aaa");
if(it != std::end(map)) {
  auto& v = it->second;
  // modify v
}
```
It seems it does not work for me (right now I am testing your branch with additional hash argument for find() operation). I get const vector from non-const iterator. It is probably caused by:
```
        using value_type = const typename hopscotch_hash::value_type;
```
in https://github.com/Tessil/hopscotch-map/blob/add_hash_parameter/src/hopscotch_hash.h#L610 and directly using `std::vector` and `std::list` iterators on `std::pair<key, value>`.

Can you confirm that is an issue?

**Comment by Tessil** [comment]
Hi,

It's an expected behaviour. See point 4 in ["Differences compare to std::unordered_map"](https://github.com/Tessil/hopscotch-map#differences-compare-to-stdunordered_map).

You have to do:
```
tsl::hopscotch_map<std::string, std::vector<int>> map;
auto it = map.find("aaa");
if(it != std::end(map)) {
  auto& v = it.value();
  // modify v
}
```

The hash map stores `std::pair<Key, T>` instead of `std::pair<const Key, T>` so that the move-constructor can be called on the pair when the pair is moved inside the bucket array (not a problem with `std::unordered_map` as they move a pointer to a node and not the pair itself).

The iterator can't just return a modifiable reference to `std::pair<Key, T>` because if the client changes the key, the map will be inconsistent. That's why the iterator returns `const& std::pair<Key, T>` and why you have to use `value()`.

**Comment by mpusz** [comment]
My bad, I should have find it by myself ;-( Sorry for taking your time and thanks again for a great support :-D
