### ISSUE TITLE
begin() slows down when the container size decreases

### ISSUE THREAD

**Issue by andrusha97** [Tessil/hopscotch-map#29]
It seems that method `begin()` becomes slower after I remove some elements. Here is a simple test https://gist.github.com/andrusha97/de6b63f48aca45a6b04b4e968c34289b
I guess it's because this method scans buckets sequentially until it finds a non-empty one, and `erase` never reduces the number of buckets. Also if this is the case, iteration over all elements probably takes `O(c.capacity())` and not `O(c.size())`.

Could you confirm that I understand things right? I'd like iterators to have more "traditional" complexities. Could you recommend how to deal with this? Should I monitor load factor and shrink containers manually?

**Comment by Tessil** [comment]
Yes, you understand it right. When `begin()` is called, we search for the first non-empty bucket. It can take up to `O(capacity)` in the worst case, which is when the map is empty.

It would be possible to remember the first non-empty bucket but it would just move the problem to the `erase()` function. Without more bookkeeping to skip empty buckets (which would make the map uses more memory and slow down the insert/erase operations), iterating through the map is in `O(capacity)` instead of `O(size)` (it's the case for all maps using open-addressing as far as I know). I should add that to the documentation.

Either you call `shrink_to_fit()` manually after some `erase()` operations or I could try to add a `min_load_factor()` similar to what `google::dense_hash_map` is doing. It shrinks the map when it goes below some threshold load factor (but set as 0 by default).

**Comment by andrusha97** [comment]
Thanks for your reply! I think I'm fine with shrinking maps manually.
