### ISSUE TITLE
Warnings with -Wshadow flag

### ISSUE THREAD

**Issue by ksergey** [Tessil/hopscotch-map#30]
Gcc produces warnings if compile with flag -Wshadow.

```
/home/ksergey/dev/bitfinex_gateway_ng/deps/zerofw/deps/hopscotch-map/src/hopscotch_set.h:460:34: warning: declaration of ‘count’ shadows a member of ‘tsl::hopscotch_set<Key, Hash, KeyEqual, Allocator, NeighborhoodSize, StoreHash, GrowthPolicy>’ [-Wshadow]

/home/ksergey/dev/bitfinex_gateway_ng/deps/zerofw/deps/hopscotch-map/src/hopscotch_set.h:461:35: warning: declaration of ‘count’ shadows a member of ‘tsl::hopscotch_set<Key, Hash, KeyEqual, Allocator, NeighborhoodSize, StoreHash, GrowthPolicy>’ [-Wshadow]
     void reserve(size_type count) { m_ht.reserve(count); }

```

**Comment by Tessil** [comment]
Thank you for the report.

I can't really check right now, but I think the problem is that the count parameter shadows the count method. I'll make the correction next week.

**Comment by Tessil** [comment]
Sorry for the delay, I was a bit busy lately.

I checked the issue more into details and I'm a bit confused with the warning. It seems that GCC is quite zealous with its warning (even though the `count` parameter has the same name as the `count` method they can't ever be mixed up as they are used completely differently).

For example the following will compile with `-Wshadow`:

```c++
class A {
public:    
    void count(int key) const {
        std::cout << "count " << key << std::endl;
    }
    
    void reserve(std::size_t count) {
        std::cout << "reserve " << count << std::endl;
    }
};
```

But not the following.

```c++
class A {
public:    
    template<typename K>
    void count(K key) const {
        std::cout << "count " << key << std::endl;
    }
    
    void reserve(std::size_t count) {
        std::cout << "reserve " << count << std::endl;
    }
};
```

No warning on both with clang. So is it a bug with GCC or is it intentional?

I will investigate a bit more, otherwise if it's really important I can just rename the `count` parameter to `count_`.

**Comment by ksergey** [comment]
Looks like bug with GCC:
https://stackoverflow.com/questions/2958457/gcc-wshadow-is-too-strict

The fix is not fix our case.

**Comment by Tessil** [comment]
Yes, it's another bug that was corrected. I checked the bug tracker of GCC and the bug affecting us doesn't seem to be there. I will see if I can open an issue when I have time.

Nonetheless I renamed the `count` parameter to `count_` to bypass the bug. You should not have any warning now with `-Wshadow`.
