### ISSUE TITLE
The CMake configuration is not compatible with CMake 3.1.

### ISSUE THREAD

**Issue by mlaveaux** [Tessil/hopscotch-map#37]
The CMake configuration has its minimum required version set to 3.1. However, the `cxx_std_11 ` constant passed to `target_compile_features` has only been introduced in CMake 3.8. The result is that for versions 3.1 to 3.7 an error will appear that this value does not exist.

The easiest solution would be to increase the minimum required version to 3.8. I have looked for other solutions to require C++11, but they are not really satisfying. It is not possible to require the C++11 compiler switch via the `CXX_STANDARD` property for interface libraries. Another, more involved, attempted solution was to specifically determine what compiler features the project needs from the list of features available in 3.1. This includes for example `cxx_auto_type` and `cxx_nullptr`. However, CMake only knows about these features for GCC and Clang, so that is also not an option. 

Another kind of solution would be that the target feature will only be set when configuring with CMake 3.8 via a version condition. For versions 3.1 to 3.7 it could print a warning, determine whether the `CXX_STANDARD` variable was set or it would simply fail during compilation.

**Comment by Tessil** [comment]
Hello,

Thank you for your report. I determined the minimum version by checking the functions I used and not their parameters, I should have tested that.

In the end I choose to just check the version of CMake before calling the function. As C++11 is the default mode for most compiler since some time, people may not set `CXX_STANDARD` and I don't want to clutter the output with invalid warnings. If an user use an old version of CMake with an old compiler without setting the C++11 flag, I think they will quickly notice the problem.
