### ISSUE TITLE
Bad insertion time of uint64_t on the latest version (February 7th)

### ISSUE THREAD

**Issue by mpusz** [Tessil/hopscotch-map#4]
Hi,

I tried your project yesterday and compared its performance on Windows (VS2015) and Linux (gcc 5.3) vs std::unordered_map. I have 2 use cases for some 'struct A':
a) `tsl::hopscotch_map<std::string, A&>` or `tsl::hopscotch_map<gsl::cstring_span<>, A&>`
b) `tsl::hopscotch_map<uint64_t, A&>`
I must say that for first use case hopscotch_map performed much better than std::unordered_map on both Windows and Linux. However the second use case on Linux has really bad performance. I measured the time of 70.000 insertions of unique uint64_t key/values pairs (and verified they have unique hash values too) and then the cleanup of such a container. The result was more than 100x times worse performance of tsl::hopscotch_map. It looks strange to me as use case a) works at the same speed. I tried to analyze the issue with linux perf tools but didn't have much time for that. Do you have any ideas what is wrong?

**Comment by Tessil** [comment]
Hi,

I quickly tested to relaunch the [benchmark](https://github.com/Tessil/hash-table-shootout) for 2 000 000,  4 000 000 and  6 000 000 keys and at first glance it seems there is no regression compare to previous versions (with gcc 6.3).

Do you have a small code snippet that can reproduce the behaviour so I can check on my side?

**Comment by mpusz** [comment]
Thanks for verifying that. Unfortunately I do not have anything I could share right now. If I will have time I will try to create such a small project and will share it with you.

**Comment by mpusz** [comment]
Made it :-)
See here: https://gist.github.com/mpusz/7c0c2f437a2b9fa9eb12bd68e4eb849b
It might end up to be hash<std::uin64_t> issue nevertheless the difference in performance is huge...

**Comment by Tessil** [comment]
Thank you.

I checked a bit and it seems there is a bad distribution due to a mix between the multiple of two growth in the map and the way the hash is computed. Most of the values end up in the overflow list which is just a linked-list as they always end-up in the same neighbourhood (even if the bucket array grows).

Even if `map.size()` returns 70 000, `map.bucket_count()` returns 128. There are 69 884 elements that end-up in the overflow list.

Two ways to change that.
* Change the growth factor to 3, loosing the fast modulo optimization. `tsl::hopscotch_map<Code, A&, std::hash<Code>, std::equal_to<Code>, std::allocator<std::pair<Code, A&>>, 62, std::ratio<3, 1>> map`.

Benchmark | Time | CPU | Iterations
--- | --- | ---| ---
BM_std    |   16723078 ns   | 16739782 ns  |       42
BM_tsl      | 11565849 ns   | 11576798 ns  |       60

* Change the hash function. Something like (which end-up to be slower):

```c++
std::size_t operator()(const Code & c) const {
    return CityHash64(c.txt, 6);
}
```
Benchmark | Time | CPU | Iterations
--- | --- | ---| ---
BM_std    |   23676483 ns  | 23699765 ns   |      29
BM_tsl     |  14391753 ns   | 14405732 ns    |     49

I have to check a little bit more if there are some ways to avoid that.

**Comment by mpusz** [comment]
I thought that hash function might be the issue here but I wanted you to be aware of it. Maybe you will find some nice solution for such cases.
Thanks for your time, analysis and providing me with possible fixes!

**Comment by Tessil** [comment]
In the end there seems to be no other solution, the combination of the hash + the power of two modulo give a really bad distribution.

I quickly tested with other hash maps, `google::dense_hash_map` and `spp::sparse_hash_map`, which also use power of two sizes (for [fast modulo](https://en.wikipedia.org/wiki/Modulo_operation#Performance_issues)), and they also end-up with worse performance than `std::unordered_map`.

So if you want to use `tsl::hopscotch_map` for this use-case, either change the hash or the way the map grows.
